### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by Aurailus** [ASDAlexander77/TypeScriptLua#5]
Hi there, I'm super interested in using this project for a Lua project of mine.
Unfortunately, your build process uses a .cmd file and my project is cross-platform (and I am on Linux). Is it possible to convert this to a cross-platform solution such as a node script? The actual functionality of prepublish_npm.cmd is quite simple and could easily be fixed.

**Comment by ASDAlexander77** [comment]
this is written in TypeScript so you can use on any system

**Comment by Aurailus** [comment]
Thanks!
